title: MadridLee Blog
description: MadridLee's personal blog hosted on GitHub Pages.
url: "https://madridlee.github.io"
baseurl: "/lan"
theme: minima
lang: zh-CN
timezone: Asia/Shanghai
author:
  name: MadridLee

header_pages:
  - about.md

plugins:
  - jekyll-feed
